- Athena
- AppSync
- Batch
- Cloudâ€‹Formation
- Comprehend
- DynamoDB
- EC2
- EKS
- EMR
- Fargate
- FSx
- Glue
- HealthLake
- Kendra
- Lambda
- Lake Formation
- Neptune
- QuickSight
- S3
- SageMaker
- SNS
- Step Functions
